name: fa_dart_core
description: Official FA Flutter core package.
version: 2.0.0+2
author: Ayush P Gupta <ayushpguptaapg@gmail.com>
homepage: https://github.com/FieldAssist/fa_dart_core.git

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rxdart: ^0.27.3
  intl: ^0.17.0
  jiffy: ^5.0.0

  # Logger
  fa_dart_logger:
    git:
      url: https://github.com/FieldAssist/fa_dart_logger.git
      ref: main

dev_dependencies:
  test: ^1.20.1
